#!/usr/bin/env python3

import argparse as argp
import collections as col
import fileinput
import gzip
import pathlib as pl
import re
import sys

import pandas as pd


def parse_command_line():
    """The CLI parser hardcodes
    a few assumption about the
    input that make sense qua
    construction for callsets
    relative to personalized
    reference genomes.

    Hence, the defaults are set
    to TRUE.

    The tool is only designed for VCF
    files generated by callers that can
    report the variant supporting reads
    (for now: Sniffles2)
    """

    parser = argp.ArgumentParser()

    parser.add_argument(
        "--autosomes-only",
        type=bool,
        default=True,
        dest="autosomes_only",
        help="Consider only variants on autosomes. Fixed to TRUE!"
    )

    parser.add_argument(
        "--variant-reads", "-o",
        type=lambda x: pl.Path(x).resolve(strict=False),
        dest="variant_reads",
        help="Out file for all read/genotype information"
    )

    parser.add_argument(
        "--subtract-sites", "-s",
        type=lambda x: pl.Path(x).resolve(strict=True),
        dest="subtract_sites",
        help="Complementary vcf with sites to substract from input"
    )

    parser.add_argument(
        "--reference-id", "-r",
        type=str,
        default="PRG",
        dest="ref_id",
        help="Short identifier of reference used. Default: PRG"

    )

    args = parser.parse_args()

    # check assumptions
    if not args.autosomes_only:
        raise RuntimeError(f"Hardcoded assumptions violated: {args}")

    sys.argv = sys.argv[:1]

    return args


def read_subtract_sites(file_path):

    subtract_sites = set()
    with gzip.open(file_path, "rt") as vcf:
        for line in vcf:
            if line.startswith("#"):
                continue
            chrom, pos = line.split()[:2]
            subtract_sites.add((chrom, pos))

    return subtract_sites


def main():

    args = parse_command_line()

    subtract_sites = read_subtract_sites(args.subtract_sites)

    # for reference - VCF header
    # [0]CHROM  POS     ID      REF     ALT     QUAL    FILTER  [7]INFO    [8]FORMAT  [9]SAMPLE

    # 2024-12-04 following discussion w/ Jana: presumably, genotyping on chrX should
    # also lead to acceptable results for male samples, hence extend below regexp
    # to include X
    match_chrom = re.compile("^chr[0-9X]+")

    ref_id = args.ref_id.upper()
    gt_mapping = {
        "1/1": f"{ref_id}_HOM",
        "0/1": f"{ref_id}_HET",
        "1/0": f"{ref_id}_HET"
    }

    vcf_records = 0
    skipped_gt = 0
    skipped_loc = 0
    skipped_site = 0

    collect_read_gt = col.defaultdict(col.Counter)

    for line in fileinput.input(encoding="utf-8"):
        if line.startswith("#"):
            continue
        vcf_records += 1
        if match_chrom.match(line) is None:
            skipped_loc += 1
            continue
        columns = line.strip().split()

        site = columns[0], columns[1]
        if site in subtract_sites:
            skipped_site += 1
            continue

        sample_gt = columns[9].split(":")[0]
        gt = gt_mapping.get(sample_gt, None)
        if gt is None:
            skipped_gt += 1
            continue

        for item in columns[7].split(";"):
            if not item.startswith("RNAMES"):
                continue
            read_names = item.strip("RNAMES=")

            for rn in read_names.split(","):
                collect_read_gt[rn][gt] += 1

            break

    df = pd.DataFrame.from_dict(collect_read_gt, orient="index")
    df.fillna(0, inplace=True)
    df.index.name = "read_name"
    df = df.astype(int)

    args.variant_reads.parent.mkdir(exist_ok=True, parents=True)
    df.to_csv(args.variant_reads, sep="\t", header=True, index=True)

    sys.stdout.write(f"Reference_processed\t{ref_id}\n")
    sys.stdout.write(f"VCF_records_processed\t{vcf_records}\n")
    sys.stdout.write(f"Skipped_records_location\t{skipped_loc}\n")
    sys.stdout.write(f"Skipped_records_site\t{skipped_site}\n")
    sys.stdout.write(f"Skipped_records_genotype\t{skipped_gt}\n")

    return 0


if __name__ == "__main__":
    main()
