
input_file_ext:
  - fastq.gz
  - fasta.gz
  - fq.gz
  - fa.gz
  - fna.gz

reference_genomes:
  mock-ref: /home/sebastian/Data/Git/smk-longread-variant-calling-project/workflow-smk-longread-variant-calling/config/testing/mock_hg38.fa

run_hifi_aligner:
  - minimap2

minimum_sv_length_call: 50
minimum_mapq: 20
minimum_coverage: 5
minimum_alignment_length: 1000