
input_file_ext:
  - fastq.gz
  - fasta.gz
  - fq.gz
  - fa.gz
  - fna.gz

reference_genomes:
  t2tv2: GCA_009914755.4_T2T-CHM13v2.0.fasta
  hg38: GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fasta

run_hifi_aligner:
  - minimap2
  - pbmm2
  - lra

# only v1.5.0+ supports low-error
# ONT reads (>=10.4)
deepvariant: deepvariant_1.5.0.sif
deepvariant_models:
  hifi: PACBIO
  ont: ONT_R104

call_chromosomes:
  - chr20
