
input_file_ext:
  - fastq.gz
  - fasta.gz
  - fq.gz
  - fa.gz
  - fna.gz

reference_genomes:
  t2tv2: GCA_009914755.4_T2T-CHM13v2.0.fasta
  hg38: GCA_000001405.15_GRCh38_no_alt_plus_hs38d1_analysis_set.fasta

run_hifi_aligner:
  - minimap2
  - pbmm2
  - lra

run_hifi_sv_toolchain:
  - minimap2, cuteSV
  - lra, sniffles

run_hifi_short_toolchain:
  - minimap2, DeepVariant

####################################
### GENERAL TOOL RUNTIME PARAMETERS
####################################

### PARAMETERS FOR SHORT VARIANT CALLING

# only v1.5.0+ supports low-error
# ONT reads (>=10.4)
deepvariant: deepvariant_1.5.0.sif
deepvariant_models:
  hifi: PACBIO
  ont: ONT_R104

# This is used to split the potentially
# large short variant callsets
# (w/o any other filtering)
# by variant type
# (bcftools 'view --types' option)
split_short_calls:
  snv: snps
  indel: indels
  other: mnps,ref,bnd,other

### PARAMETERS FOR LONG VARIANT CALLING

# SVs are defined as variants
# of at least 50 bp.
# This parameter is set below
# that threshold to produce some
# overlap with the short variant
# callers (in bp)
minimum_sv_length_call: 35

# ignore alignments with MAPQ
# below this threshold
minimum_mapq: 20

# ignore regions/candidates with read
# coverage/support below this threshold
# (interpretation is tool-specific)
minimum_coverage: 5

# ignore reads/alignments with an alignment
# length below this threshold (in bp)
minimum_alignment_length: 1000
