
input_file_ext:
  - fastq.gz
  - fasta.gz
  - fq.gz
  - fa.gz
  - fna.gz

# Set in project-specific
# config - which reference
# genomes to use?
# reference_genomes:
#   label: fasta_file_name

run_hifi_aligner:
  - minimap2
  - pbmm2
  - lra

run_hifi_sv_toolchain:
  - minimap2, cuteSV
  - lra, sniffles

run_hifi_short_toolchain:
  - minimap2, DeepVariant

####################################
### GENERAL TOOL RUNTIME PARAMETERS
####################################

### PARAMETERS FOR BASIC QC /
### READ DEPTH COMPUTATION WITH MOSDEPTH

# mosdepth window size and quantize_*
# option apply to the whole-genome
# setting
mosdepth_window_size: 10000
# MUST BE LISTS
mosdepth_quantize_steps: [0, 1, 5, 10, 15]
mosdepth_quantize_names:
  - NO_COV
  - LOW_COV
  - CALLABLE
  - GOOD_COV
  - HIGH_COV

# mosdepth coverage thresholds
# apply to user-supplied regions
# of interest (QC regions) that
# are expected to exhibit good
# coverage
# MUST BE A LIST
mosdepth_cov_thresholds: [0, 1, 5, 10, 15]

# NB: this should be set to the
# same value as for the long
# variant calling (default: 20).
# Adding 0 to the list enables
# checking if a call could be
# made at a lower MAPQ
# MUST BE A LIST
mosdepth_min_mapq: [0, 20]


### PARAMETERS FOR SHORT VARIANT CALLING

# only v1.5.0+ supports low-error
# ONT reads (>=10.4)
deepvariant: deepvariant_1.5.0.sif
deepvariant_models:
  hifi: PACBIO
  ont: ONT_R104

# This is used to split the potentially
# large short variant callsets
# (w/o any other filtering)
# by variant type
# (bcftools 'view --types' option)
split_short_calls:
  snv: snps
  indel: indels
  other: mnps,ref,bnd,other

### PARAMETERS FOR LONG VARIANT CALLING

# SVs are defined as variants
# of at least 50 bp.
# This parameter is set below
# that threshold to produce some
# overlap with the short variant
# callers (in bp)
minimum_sv_length_call: 35

# ignore alignments with MAPQ
# below this threshold
minimum_mapq: 20

# ignore regions/candidates with read
# coverage/support below this threshold
# (interpretation is tool-specific)
minimum_coverage: 5

# ignore reads/alignments with an alignment
# length below this threshold (in bp)
minimum_alignment_length: 1000
