# This config file exists as reference;
# using reference containers is likely a
# project-specific decision and should
# thus be configured in the project config

use_reference_container: False

reference_container_names:
  - sif_file_name_1
  - sif_file_name_2

reference_container_store: /gpfs/project/projects/medbioinf/data/ref_container
