
use_reference_container: True

reference_container_names:
  - ncbi-t2t-chm13hg002_v2_incl_chr_prefix
  - ncbi-hg38-bwaidx_v0

reference_container_store: /gpfs/project/projects/medbioinf/data/ref_container
